exp_id: GSE217517 
preprocessing:
  ### Union or intersect accepted
  mode: intersect            
  ### Minimum 0, maximum 1. Ratio of samples required for gene to be non-zero
  non_zeros_required: 0.2    
### File path to be used for saving. Remember to have .rds as file extension
save_file_path: 2_datapreprocessing_intersect_0-2.rds
